<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Core" />
    <PackageReference Include="Microsoft.Agents.Builder" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="OpenTelemetry.Exporter.Console" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
	</ItemGroup>
</Project>
