<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Microsoft.Agents.A365.Notifications</AssemblyName>
    <RootNamespace>Microsoft.Agents.A365.Notifications</RootNamespace>
    <!-- NuGet Package Properties -->
    <PackageId>Microsoft.Agents.A365.Notifications</PackageId>
    <Title>Microsoft Agent 365 Notifications SDK</Title>
    <Description>Microsoft Agent 365 Notifications SDK, providing functionality to handle Agent 365 notifications.</Description>
    <Summary>Microsoft Agent 365 Notifications SDK - functionality to handle Agent 365 Notifications</Summary>
    <Product>Microsoft Agent 365 Notifications SDK</Product>
    <PackageTags>Microsoft;Agent365;A365;Notifications;AgentsSDK;ActivityProtocol;AI;Agents</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Agents.Builder" />
  </ItemGroup>
</Project>

