<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>Microsoft.Agents.A365.Tooling.AzureFoundry</AssemblyName>
		<RootNamespace>Microsoft.Agents.A365.Tooling.AzureFoundry</RootNamespace>
		<TargetFramework>net8.0</TargetFramework>
		<LangVersion>latest</LangVersion>

		<!-- NuGet Package Properties -->
		<PackageId>Microsoft.Agents.A365.Tooling.AzureFoundry</PackageId>
		<Title>Microsoft Kairo AzureFoundry Integration</Title>
		<Description>A .NET SDK that integrates Microsoft Kairo with AzureFoundry, providing tooling functionalities.</Description>
		<Summary>Microsoft Kairo AzureFoundry Tooling Integration - Provides a way to add A365 MCP Servers</Summary>
		<Product>Microsoft Agents A365 SDK AzureFoundry Tooling Integration</Product>
		<PackageTags>Microsoft;Kairo;AzureFoundry;OpenTelemetry;AI;Agents;Tooling</PackageTags>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="D:\Agent365\dotnet\sdk\..\\CHANGELOG.md" />
	</ItemGroup>

	<ItemGroup>
		<!-- Azure Foundry related package -->
		<PackageReference Include="Azure.AI.Agents.Persistent" />

		<!-- Source Link Support -->
		<PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
		<PackageReference Include="ModelContextProtocol.Core" />
		<PackageReference Include="Microsoft.Agents.Authentication.Msal" />
		<PackageReference Include="Microsoft.Agents.Hosting.AspNetCore" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Core\Microsoft.Agents.A365.Tooling.csproj" />
	</ItemGroup>
</Project>
